### ISSUE TITLE
I didn't understand the await part.

### ISSUE THREAD

**Issue by SirEduRs** [4O4/node-mtasa#1]
There's someone to explain about await, I didn't understand the "some param" part

**Comment by 4O4** [comment]
"some param" is just any parameter you want to pass to the remote procedure. You can pass any number of parameters or none at all, it depends what your implementation on Lua side is. If your Lua procedure (which is exported via http in meta.xml) takes two parameters for example, then you probably want to pass two parameters.

`async/await` and promises are javascript language features, you can find more info about them here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
